# Generated by Django 2.2.17 on 2021-03-25 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=16)),
                ('isAdmin', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poemID', models.BigIntegerField(unique=True)),
                ('likes', models.BigIntegerField(default=0)),
                ('articleTitle', models.CharField(max_length=100)),
                ('text', models.FileField(upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poemApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.BigIntegerField(unique=True)),
                ('text', models.CharField(default='', max_length=1000)),
                ('likes', models.BigIntegerField(default=0)),
                ('poem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poemApp.Poem')),
                ('replyTo', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment', to='poemApp.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poemApp.User')),
            ],
        ),
    ]
