# Generated by Django 2.2.17 on 2021-03-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poemApp', '0002_auto_20210326_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentID',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='poemID',
        ),
    ]
