# Generated by Django 2.2.17 on 2021-03-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemApp', '0003_auto_20210329_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poem',
            name='articleTitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
