# Generated by Django 2.2.17 on 2021-03-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemApp', '0004_auto_20210329_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=models.TextField(),
        ),
    ]
