# Generated by Django 2.2.17 on 2021-03-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemApp', '0006_poem_addeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
