# Generated by Django 2.2.17 on 2021-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemApp', '0010_auto_20210330_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
