# Generated by Django 2.2.17 on 2021-03-30 16:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poemApp', '0011_auto_20210330_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
